[module/battery]
type = internal/battery
full-at = 99
battery = BAT1
adapter = ACAD
poll-interval = 2
time-format = %H:%M
format-charging = <animation-charging> <label-charging>
format-charging-background = ${color.shade3}
format-charging-padding = 1
format-discharging = <ramp-capacity> <label-discharging>
format-discharging-background = ${color.shade3}
format-discharging-padding = 1
format-full = <label-full>
format-full-prefix = 
format-full-background = ${color.shade3}
format-full-padding = 1
label-charging = "%percentage%% "
label-discharging = "%percentage%% "
label-full = " Full "
ramp-capacity-0 = 
ramp-capacity-1 = 
ramp-capacity-2 = 
ramp-capacity-3 = 
ramp-capacity-4 = 
animation-charging-0 = 
animation-charging-1 = 
animation-charging-2 = 
animation-charging-framerate = 750

[module/date]
type = internal/date
interval = 1.0
time = " %I:%M %p"
time-alt = " %a, %d %b %Y"
format = <label>
format-background = ${color.shade2}
format-padding = 1
label = %time%

[module/network]
type = internal/network
interface = wlan0
interval = 1.0
accumulate-stats = true
unknown-as-up = true
format-connected = <ramp-signal> <label-connected>
format-connected-background = ${color.shade5}
format-connected-padding = 1
format-disconnected = <label-disconnected>
format-disconnected-prefix = 
format-disconnected-background = ${color.shade5}
format-disconnected-padding = 1

label-connected = "%{A1:alacritty -e nmtui &:}%essid% %{A}"
label-disconnected = "%{A1:alacritty -e nmtui &:} Offline %{A}"

ramp-signal-0 = 
ramp-signal-1 = 
ramp-signal-2 = 

[module/pulseaudio]
type = internal/pulseaudio
interval = 5

format-volume = <ramp-volume> <label-volume>
format-volume-background = ${color.shade4}
format-volume-padding = 1

format-muted = <label-muted>
format-muted-prefix = 
format-muted-background = ${color.shade4}
format-muted-padding = 1

label-volume = "%percentage%%"
label-muted = "MUTE"

ramp-volume-0 = 
ramp-volume-1 = 
ramp-volume-2 = 

click-left = pactl set-sink-mute @DEFAULT_SINK@ toggle
scroll-up = pactl set-sink-volume @DEFAULT_SINK@ +5%
scroll-down = pactl set-sink-volume @DEFAULT_SINK@ -5%

[module/title]
type = internal/xwindow
format = <label>
format-background = ${color.shade2}
format-padding = 1
label = " %title%"
label-maxlen = 30
label-empty = " Desktop"

[module/workspaces]
type = internal/xworkspaces
pin-workspaces = true
enable-click = true
enable-scroll = true

format = <label-state>

label-active = %name%
label-active-foreground = ${color.shade8}
label-active-padding = 1

label-occupied = %name%
label-occupied-foreground = ${color.shade2}
label-occupied-padding = 1

label-urgent = %name%
label-urgent-foreground = ${color.shade1}
label-urgent-padding = 1

label-empty =

;; _-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_

[module/localip]
type = custom/script
exec = ip -4 route get 1.1.1.1 2>/dev/null | awk '/src/{for(i=1;i<=NF;i++) if($i=="src") print $(i+1)}'
interval = 10
format =  <label>
format-background = ${color.shade5}
format-padding = 1
